### ISSUE TITLE
__pycache__ ディレクトリがコミットされている

### ISSUE THREAD

**Issue by tamanobi** [mayukorin/toDo#1]
__pycache__ ディレクトリは環境ごとにキャッシュとして生成されるものです。生成物はコミットしたとしても、リポジトリの容量が大きくなってしまう上、ほかの共同開発者にとって邪魔なものになります。

削除した上で、 .gitignore に追加しましょう。

**Comment by mayukorin** [comment]
ご指摘をありがとうございます。削除をしました。

**Comment by tamanobi** [comment]
対応が終わったら、Issueを閉じてください！
